# Generated by Django 6.1.2 on 2026-10-07 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
                ('issued_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed With Errors'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.PositiveIntegerField()),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('file', models.FileField(blank=True, upload_to='certificates/%Y/%m/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='generator.job')),
            ],
            options={
                'ordering': ['row_index'],
                'indexes': [models.Index(fields=['job', 'status'], name='generator_c_job_id_08636a_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'row_index'), name='unique_row_per_job')],
            },
        ),
    ]
